<?php
/**
 * Created by PhpStorm.
 * User: jarngotostos
 * Date: 12/1/18
 * Time: 8:48 PM
 */

namespace App\Controller\EasyAdmin;

use AlterPHP\EasyAdminExtensionBundle\Controller\AdminController;
use App\Entity\Student;
use App\Entity\Subject;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Doctrine\ORM\EntityRepository;

class EventController extends AdminController
{
    /**
     * Allows applications to modify the entity associated with the item being
     * created before persisting it.
     *
     * @param object $entity
     */
    protected function prePersistEntity($entity)
    {
        if (in_array('ROLE_ADMIN', $this->getUser()->getRoles())) {
            $entity->setTeacher(null);
        } else {
            $entity->setTeacher($this->getUser());
        }

        return parent::prePersistEntity($entity); // TODO: Change the autogenerated stub
    }

    /**
     * Creates the form builder of the form used to create or edit the given entity.
     *
     * @param object $entity
     * @param string $view The name of the view where this form is used ('new' or 'edit')
     *
     * @return \Symfony\Component\Form\FormBuilder
     */
    protected function createEventEntityFormBuilder($entity, $view)
    {
        $adminChoices = [
            'HOLIDAY' => 'HOLIDAY',
            'SCHOOL EVENT' => 'SCHOOL_EVENT',
            'EXAM' => 'EXAM',
        ];
        $teacherChoices = [
            'QUIZ' => 'QUIZ',
            'HOMEWORK' => 'HOMEWORK',
            'ACTIVITY' => 'ACTIVITY'
        ];

        $builder = parent::createEntityFormBuilder($entity, $view);
        $builder->remove('teacher');

        $builder
            ->add('dateStart', DateType::class, [
                'label' => 'Start',
                'years' => range(date('Y'), date('Y') + 1),
                'months' => range(1, 12),
                'days' => range(1, 31),
            ])
            ->add('dateEnd', DateType::class, [
                'label' => 'End',
                'years' => range(date('Y'), date('Y') + 1),
                'months' => range(1, 12),
                'days' => range(1, 31),
                'required' => false
            ])
            ->add('student', EntityType::class, [
                'class' => Student::class,
                'multiple' => true,
                'query_builder' => function (EntityRepository $repository) {
                    return $repository->createQueryBuilder('s')
                        ->where('s.teacher = :teacher')
                        ->setParameter('teacher', $this->getUser());
                },
                'attr' => [
                    'data-widget' => 'select2'
                ]
            ])
            ->add('subject', EntityType::class, [
                'class' => Subject::class,
                'required' => true,
                'attr' => [
                    'data-widget' => 'select2'
                ]
            ])
        ;

        if (in_array('ROLE_ADMIN', $this->getUser()->getRoles())) {
            $builder->remove('subject');
            $builder->remove('student');
            $builder->add('type', ChoiceType::class, [
                'choices' => $adminChoices,
                'attr' => [
                    'data-widget' => 'select2'
                ]
            ]);
        } else {
            $builder->add('type', ChoiceType::class, [
                'choices' => $teacherChoices,
                'attr' => [
                    'data-widget' => 'select2'
                ]
            ]);
        }

        return $builder;
    }
}
