<?php
/**
 * Created by PhpStorm.
 * User: jarngotostos
 * Date: 12/2/18
 * Time: 6:59 AM
 */

namespace App\Controller\EasyAdmin;

use AlterPHP\EasyAdminExtensionBundle\Controller\AdminController;
use App\Entity\Student;
use App\Entity\Subject;
use App\Entity\TaskType;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class GradesController extends AdminController
{
    /**
     * Allows applications to modify the entity associated with the item being
     * created before persisting it.
     *
     * @param object $entity
     * @throws \Exception
     */
    protected function prePersistEntity($entity)
    {
        $teacher = $this->getUser();

        $entity
            ->setDate(new \DateTime())
            ->setTeacher($teacher);
        return parent::prePersistEntity($entity); // TODO: Change the autogenerated stub
    }

    /**
     * Creates the form builder of the form used to create or edit the given entity.
     *
     * @param object $entity
     * @param string $view The name of the view where this form is used ('new' or 'edit')
     *
     * @return FormBuilder
     */
    protected function createGradesEntityFormBuilder($entity, $view)
    {
        $teacher = $this->getUser();
        $builder = parent::createEntityFormBuilder($entity, $view);

        $builder
            ->remove('date')
            ->remove('teacher')
        ;

        $builder
            ->add('student', EntityType::class, [
                'class' => Student::class,
                'query_builder' => function (EntityRepository $repository) use ($teacher) {
                    return $repository->createQueryBuilder('s')
                        ->where('s.teacher = :teacher')
                        ->setParameter('teacher', $teacher);
                },
                'attr' => [
                    'data-widget' => 'select2'
                ]
            ])
            ->add('subject', EntityType::class, [
                'class' => Subject::class,
                'required' => true,
                'attr' => [
                    'data-widget' => 'select2'
                ]
            ])
            ->add('task', EntityType::class, [
                'required' => true,
                'class' => TaskType::class,
                'attr' => [
                    'data-widget' => 'select2'
                ]
            ])
        ;

        return $builder;
    }

    /**
     * Creates Query Builder instance for all the records.
     *
     * @param string $entityClass
     * @param string $sortDirection
     * @param string|null $sortField
     * @param string|null $dqlFilter
     *
     * @return \Doctrine\ORM\QueryBuilder The Query Builder instance
     */
    protected function createListQueryBuilder($entityClass, $sortDirection, $sortField = null, $dqlFilter = null)
    {
        $teacher = $this->getUser();
        $qb = parent::createListQueryBuilder($entityClass, $sortDirection, $sortField, $dqlFilter);

        $qb->where('entity.teacher = :teacher')
            ->setParameter('teacher', $teacher)
            ->orderBy('entity.student', 'DESC')
        ;

        return $qb;
    }
}
