<?php
/**
 * Created by PhpStorm.
 * User: jarngotostos
 * Date: 12/2/18
 * Time: 12:43 PM
 */

namespace App\Controller\EasyAdmin;

use AlterPHP\EasyAdminExtensionBundle\Controller\AdminController;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class HomeworkController extends AdminController
{
    /**
     * Allows applications to modify the entity associated with the item being
     * created before persisting it.
     *
     * @param object $entity
     */
    protected function prePersistEntity($entity)
    {
        return parent::prePersistEntity($entity); // TODO: Change the autogenerated stub
    }

    /**
     * Creates the form builder of the form used to create or edit the given entity.
     *
     * @param object $entity
     * @param string $view The name of the view where this form is used ('new' or 'edit')
     *
     * @return FormBuilder
     */
    protected function createEntityFormBuilder($entity, $view)
    {
        $builder = parent::createEntityFormBuilder($entity, $view);

        $builder->remove('createdAt');

        $builder
            ->add('title', TextType::class)
            ->add('description', TextareaType::class, [
                'required' => false
            ])
            ->add('submissionDate',DateType::class, [
                'label' => 'Submission Date',
                'years' => range(date('Y'), date('Y')),
                'months' => range(1, 12),
                'days' => range(1, 31),
            ])
        ;

        return $builder;
    }
}
